version: "3.9"
services:
  flexivpy:
    build: ..
    container_name: flexiv-py-container
    network_mode: host
    privileged: true
    command: bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../:/home/FlexivPy
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    # runtime: nvidia
    stdin_open: true
    tty: true