#
# CAUTION!!
# Changing parameters in this YAML file is dangerous!
# Before making any changes, first read the C++ code to understand what you are doing.
#
# The C++ bridge implements several security checks to make
# operation from Python very secure.
# Removing these checks or changing the bounds can result in the robot damaging itself or the surroundings.
#
#
# See function
# void parse_config_file(const std::string &filename)
# in class RobotController


# Examples:
# kImpedanceKp:  [3000.0, 3000.0, 800.0, 800.0, 200.0,  200.0,  200.0]
gripper_max_force: 20
tau_min: [-200, -200, -80, -80, -30, -30, -30]
tau_max: [200, 200, 80, 80, 30, 30, 30]
p_ub_endeff: [ 1.2, 0.9, 0.9]
p_lb_endeff: [-0.1, -0.9 , 0.01]
q_min: [-1.9, -2.4, -2.79257, -2.70527, -2.96707, -1.39627, -2.96707]
q_max: [1.9, .75, 2.79257, 2.70527, 2.96707, 4.53787, 2.96707]
max_endeff_v: 1.5
dq_min: [-1.4, -1.5, -1.7, -1.7, -1.9, -2.0, -1.9]
dq_max: [1.4, 1.5, 1.7, 1.7, 1.9, 2.0, 1.9]
gripper_min_closing_force: 20
gripper_width_close: 0.02
gripper_velocity: 0.1